export const countryCodes = {
  // Afrique (54 pays)
  "Afrique du Sud": "za",
  "Algérie": "dz",
  "Angola": "ao",
  "Bénin": "bj",
  "Botswana": "bw",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cameroun": "cm",
  "Cap-Vert": "cv",
  "Centrafrique": "cf",
  "Comores": "km",
  "Congo": "cg",
  "Côte d'Ivoire": "ci",
  "Djibouti": "dj",
  "Égypte": "eg",
  "Érythrée": "er",
  "Eswatini": "sz",
  "Éthiopie": "et",
  "Gabon": "ga",
  "Gambie": "gm",
  "Ghana": "gh",
  "Guinée": "gn",
  "Guinée équatoriale": "gq",
  "Guinée-Bissau": "gw",
  "Kenya": "ke",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libye": "ly",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Mali": "ml",
  "Maroc": "ma",
  "Maurice": "mu",
  "Mauritanie": "mr",
  "Mozambique": "mz",
  "Namibie": "na",
  "Niger": "ne",
  "Nigeria": "ng",
  "Ouganda": "ug",
  "République démocratique du Congo": "cd",
  "Rwanda": "rw",
  "Sao Tomé-et-Principe": "st",
  "Sénégal": "sn",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Somalie": "so",
  "Soudan": "sd",
  "Soudan du Sud": "ss",
  "Tanzanie": "tz",
  "Tchad": "td",
  "Togo": "tg",
  "Tunisie": "tn",
  "Zambie": "zm",
  "Zimbabwe": "zw",

  // Europe (50 pays)
  "Albanie": "al",
  "Allemagne": "de",
  "Andorre": "ad",
  "Arménie": "am",
  "Autriche": "at",
  "Azerbaïdjan": "az",
  "Belgique": "be",
  "Biélorussie": "by",
  "Bosnie-Herzégovine": "ba",
  "Bulgarie": "bg",
  "Chypre": "cy",
  "Croatie": "hr",
  "Danemark": "dk",
  "Espagne": "es",
  "Estonie": "ee",
  "Finlande": "fi",
  "France": "fr",
  "Géorgie": "ge",
  "Grèce": "gr",
  "Hongrie": "hu",
  "Irlande": "ie",
  "Islande": "is",
  "Italie": "it",
  "Kosovo": "xk",
  "Lettonie": "lv",
  "Liechtenstein": "li",
  "Lituanie": "lt",
  "Luxembourg": "lu",
  "Macédoine du Nord": "mk",
  "Malte": "mt",
  "Moldavie": "md",
  "Monaco": "mc",
  "Monténégro": "me",
  "Norvège": "no",
  "Pays-Bas": "nl",
  "Pologne": "pl",
  "Portugal": "pt",
  "République tchèque": "cz",
  "Roumanie": "ro",
  "Royaume-Uni": "gb",
  "Russie": "ru",
  "Saint-Marin": "sm",
  "Serbie": "rs",
  "Slovaquie": "sk",
  "Slovénie": "si",
  "Suède": "se",
  "Suisse": "ch",
  "Ukraine": "ua",
  "Vatican": "va",

  // Amérique du Nord (3 pays)
  "Canada": "ca",
  "États-Unis": "us",
  "Mexique": "mx",

  // Amérique centrale et Caraïbes (20 pays)
  "Antigua-et-Barbuda": "ag",
  "Bahamas": "bs",
  "Barbade": "bb",
  "Belize": "bz",
  "Costa Rica": "cr",
  "Cuba": "cu",
  "Dominique": "dm",
  "Guatemala": "gt",
  "Grenade": "gd",
  "Haïti": "ht",
  "Honduras": "hn",
  "Jamaïque": "jm",
  "Nicaragua": "ni",
  "Panama": "pa",
  "République dominicaine": "do",
  "Saint-Kitts-et-Nevis": "kn",
  "Saint-Vincent-et-les-Grenadines": "vc",
  "Sainte-Lucie": "lc",
  "Salvador": "sv",
  "Trinité-et-Tobago": "tt",

  // Amérique du Sud (12 pays)
  "Argentine": "ar",
  "Bolivie": "bo",
  "Brésil": "br",
  "Chili": "cl",
  "Colombie": "co",
  "Équateur": "ec",
  "Guyana": "gy",
  "Paraguay": "py",
  "Pérou": "pe",
  "Suriname": "sr",
  "Uruguay": "uy",
  "Venezuela": "ve",

  // Asie (49 pays)
  "Afghanistan": "af",
  "Arabie Saoudite": "sa",
  "Bahreïn": "bh",
  "Bangladesh": "bd",
  "Bhoutan": "bt",
  "Birmanie": "mm",
  "Brunei": "bn",
  "Cambodge": "kh",
  "Chine": "cn",
  "Corée du Nord": "kp",
  "Corée du Sud": "kr",
  "Émirats arabes unis": "ae",
  "Inde": "in",
  "Indonésie": "id",
  "Irak": "iq",
  "Iran": "ir",
  "Israël": "il",
  "Japon": "jp",
  "Jordanie": "jo",
  "Kazakhstan": "kz",
  "Kirghizistan": "kg",
  "Koweït": "kw",
  "Laos": "la",
  "Liban": "lb",
  "Malaisie": "my",
  "Maldives": "mv",
  "Mongolie": "mn",
  "Népal": "np",
  "Oman": "om",
  "Ouzbékistan": "uz",
  "Pakistan": "pk",
  "Palestine": "ps",
  "Philippines": "ph",
  "Qatar": "qa",
  "Singapour": "sg",
  "Sri Lanka": "lk",
  "Syrie": "sy",
  "Tadjikistan": "tj",
  "Taïwan": "tw",
  "Thaïlande": "th",
  "Timor oriental": "tl",
  "Turkménistan": "tm",
  "Turquie": "tr",
  "Viêt Nam": "vn",
  "Yémen": "ye",

  // Océanie (14 pays)
  "Australie": "au",
  "Fidji": "fj",
  "Îles Marshall": "mh",
  "Îles Salomon": "sb",
  "Kiribati": "ki",
  "Micronésie": "fm",
  "Nauru": "nr",
  "Nouvelle-Zélande": "nz",
  "Palaos": "pw",
  "Papouasie-Nouvelle-Guinée": "pg",
  "Samoa": "ws",
  "Tonga": "to",
  "Tuvalu": "tv",
  "Vanuatu": "vu",

  // Territoires et dépendances (70+)
  "Açores": "pt-20",
  "Åland": "ax",
  "Anguilla": "ai",
  "Antarctique": "aq",
  "Antilles néerlandaises": "an",
  "Aruba": "aw",
  "Bermudes": "bm",
  "Bonaire": "bq",
  "Bouvet": "bv",
  "Curaçao": "cw",
  "Géorgie du Sud": "gs",
  "Gibraltar": "gi",
  "Groenland": "gl",
  "Guadeloupe": "gp",
  "Guam": "gu",
  "Guernesey": "gg",
  "Guyane française": "gf",
  "Hong Kong": "hk",
  "Île de Man": "im",
  "Île Christmas": "cx",
  "Île Norfolk": "nf",
  "Îles Caïmans": "ky",
  "Îles Cocos": "cc",
  "Îles Cook": "ck",
  "Îles Féroé": "fo",
  "Îles Heard-et-MacDonald": "hm",
  "Îles Malouines": "fk",
  "Îles Mariannes du Nord": "mp",
  "Îles mineures éloignées des États-Unis": "um",
  "Îles Pitcairn": "pn",
  "Îles Turques-et-Caïques": "tc",
  "Îles Vierges américaines": "vi",
  "Îles Vierges britanniques": "vg",
  "Jersey": "je",
  "La Réunion": "re",
  "Macao": "mo",
  "Martinique": "mq",
  "Mayotte": "yt",
  "Montserrat": "ms",
  "Niue": "nu",
  "Nouvelle-Calédonie": "nc",
  "Polynésie française": "pf",
  "Porto Rico": "pr",
  "Sahara occidental": "eh",
  "Saint-Barthélemy": "bl",
  "Saint-Hélène": "sh",
  "Saint-Martin (FR)": "mf",
  "Saint-Martin (NL)": "sx",
  "Saint-Pierre-et-Miquelon": "pm",
  "Samoa américaines": "as",
  "Svalbard et Jan Mayen": "sj",
  "Terres australes françaises": "tf",
  "Territoire britannique de l'océan Indien": "io",
  "Tokelau": "tk",
  "Wallis-et-Futuna": "wf",

  // Drapeaux régionaux UK
  "Angleterre": "gb-eng",
  "Écosse": "gb-sct",
  "Irlande du Nord": "gb-nir",
  "Pays de Galles": "gb-wls",

  // Drapeaux régionaux Espagne
  "Catalogne": "es-ct",
  "Galice": "es-ga",
  "Pays basque": "es-pv",

  // Organisations
  "Union européenne": "eu",
  "Nations Unies": "un",
  "Ligue arabe": "arab",
  "CEFTA": "cefta",
  "Esperanto": "eo",

  // Drapeaux spéciaux
  "Drapeau arc-en-ciel": "rainbow",
  "Drapeau pirate": "pirate",
  "Drapeau trans": "transgender",
};

export function getCountryCode(countryName) {
  return countryCodes[countryName] || null;
}

export function getFlagClass(countryName) {
  const code = getCountryCode(countryName);
  return code ? `fi fi-${code}` : '';
}